### ISSUE TITLE
Why does `remake` ignore my `u0`?

### ISSUE THREAD

**Issue by bradcarman** [SciML/ModelingToolkit.jl#3661]
Take the following...

```julia
using ModelingToolkit
using ModelingToolkit: t_nounits as t, D_nounits as D
using OrdinaryDiffEq
using CairoMakie

pars = @parameters begin
    k(t)
end

vars = @variables begin
    x(t)
end

eqs = [
    D(x) ~ (k - x)
]

@mtkbuild sys = ODESystem(eqs, t, vars, pars)
prob = ODEProblem(sys, [x=>0], (0, Inf), [k => 0])
integrator = init(prob, Rodas5P())

dt=0.1
for i=1:100
    integrator.ps[sys.k] = ((i-1)*dt)^2
    step!(integrator, dt, true)
end

prob_copy = remake(prob; u0=integrator.u, p = integrator.p, tspan= (99*dt, Inf))
integrator_copy = init(prob_copy, Rodas5P(); initializealg=CheckInit())

for i=101:200
    integrator.ps[sys.k] = ((i-1)*dt)^2
    integrator_copy.ps[sys.k] = ((i-1)*dt)^2
    step!(integrator, dt, true)
    step!(integrator_copy, dt, true)
end

time = 0:dt:199*dt
time_copy = 10:dt:199*dt

fig = Figure()
ax = Axis(fig[1,1], xlabel="time [s]", ylabel="sys.x")
lines!(ax, time, integrator.sol(time; idxs=sys.x).u; label="integrator")
scatter!(ax, time_copy, integrator_copy.sol(time_copy; idxs=sys.x).u; color=:red, label="integrator_copy")
axislegend(ax; position=:lt)
fig
```

This gives the following...

![Image](https://github.com/user-attachments/assets/9053d264-ffab-404d-97c0-1d8f3f72ea59)

If I transfer the state `u0` and the parameters `p` from `integrator` to `integrator_copy`, why does `integrator_copy` start at 0 instead of 81?

using ModelingToolkit v9.79.0

**Comment by kaandocal** [comment]
Bumping this as I am also having this issue, seemingly with DAE systems:

```julia
using Catalyst
using OrdinaryDiffEq

rn = @reaction_network begin
   @equations begin
       X ~ Y
   end
   1, 0 --> X
end

prob = ODEProblem(rn, [ :Y => 5 ], (0, 1.); structural_simplify=true)
remake(prob, [ 1 ])
```

yields
```
ODEProblem with uType Vector{Float64} and tType Float64. In-place: true
Initialization status: FULLY_DETERMINED
Non-trivial mass matrix: false
timespan: (0.0, 1.0)
u0: 1-element Vector{Float64}:
 5.0
```

`remake` silently (!) ignores any changes to `u0`. After a lot of digging, it seems like something is dropping `u0` in `initializesystem`. I haven't checked if that also applies to parameters `p`. Any advice would be much appreciated!

**Comment by ChrisRackauckas** [comment]
You didn't change the `initial` value, which is a parameter. You shouldn't do the non-symbolic remake with an MTK DAE system. `remake(prob, [X => 1 ])` should do it where it'll update the parameter, and then when you solve it will update the value before solving.

If you're using Catalyst that has a known bug here since it's not on v10.

> using ModelingToolkit v9.79.0

This was fixed on v10 so closing.

**Comment by kaandocal** [comment]
I was suspecting a version issue based on other similar issues in the tracker. But the symbolic remake is probably the way to go forward. Thank you!

**Comment by bradcarman** [comment]
Why was this issue closed, I still get the same wrong result on the latest version of MTK?

<img width="878" height="656" alt="Image" src="https://github.com/user-attachments/assets/7ec4d691-2a6b-4f8b-94ca-492a49bb450c" />

If I'm doing something wrong in my MWE, please let me know what that is.

**Comment by AayushSabharwal** [comment]
It's because you're specifying both `u0` and `p` to `remake`. For every unknown `x` in your ODE, there is a parameter `Initial(x)`. When you give an exact numeric initial condition for `x`, the initialization system contains the equation `x ~ Initial(x)`, and sets `Initial(x)` to that numeric value. That's what happens when `prob` is created.

Now, `remake` takes user input as the complete source of truth. If you just specify `u0 = integrator.u`, it will copy that over to `Initial(x)` (for all unknowns). However, since you specify both `u0` and `p` it doesn't know which of the two you want to respect. As a result, `Initial(x)` is not updated from its value of 0.0 and initialization resets the unknowns back to zero.

**Comment by bradcarman** [comment]
My understanding was that `initializealg=CheckInit()` skipped initialization, so the initial equations should be ignored for the `integrator_copy`.  Is that right?  If not, what does `CheckInit()` do?

**Comment by AayushSabharwal** [comment]
`remake` runs initialization if it does not require a nonlinear solver. This can be avoided by passing `lazy_initialization = true`

**Comment by bradcarman** [comment]
OK, thanks.  So the correct code to transfer `u0` to another integrator is:

```julia
using ModelingToolkit
using ModelingToolkit: t_nounits as t, D_nounits as D
using OrdinaryDiffEq

pars = @parameters begin
    k(t)
end

vars = @variables begin
    x(t)
end

eqs = [
    D(x) ~ (k - x)
]

@mtkbuild sys = ODESystem(eqs, t, vars, pars)
prob = ODEProblem(sys, [x=>0], (0, Inf), [k => 0])
integrator = init(prob, Rodas5P())

dt=0.1
for i=1:100
    integrator.ps[sys.k] = ((i-1)*dt)^2
    step!(integrator, dt, true)
end

prob_copy = remake(prob; u0=integrator.u, tspan= (integrator.t, Inf))
integrator_copy = init(prob_copy, Rodas5P()) #; initializealg=CheckInit()

for i=101:200
    integrator.ps[sys.k] = ((i-1)*dt)^2
    integrator_copy.ps[sys.k] = ((i-1)*dt)^2
    step!(integrator, dt, true)
    step!(integrator_copy, dt, true)
end
```

<img width="798" height="612" alt="Image" src="https://github.com/user-attachments/assets/560e6e17-d7fd-45e9-8f18-4b7eb2289e22" />

**Comment by kaandocal** [comment]
It might be useful to make this a little more obvious in the documentation, and potentially add a warning - apologies if I just overlooked it, but the fact that `p` overwrites `u0` (these are treated as distinct in DifferentialEquations.jl) can be a trap!

**Comment by ChrisRackauckas** [comment]
This is generally a ModelingToolkit thing though, not just initial conditions. Because you can have things like `p1 ~ p2` with `p1 ~ missing` which means "solve for p1" and that happens in the initialization system. The way that initial values are treated actually just uses the same mechanism. You cannot generally do this before hand because your system of initial conditions can be an arbitrarily complex nonlinear system, which means it requires a Newton solve, and may require for solving the parameters first, and so it all needs to be solved at the same time... which is the initialization step. So there's nothing special here, but maybe we should make an FAQ entry that basically says that `u0` and `p` objects are not really complete until the initialization phase is ran. It stores all of the information for running the initialization phase but only after that will your `u0` and `p` be the values at the start, even if your symbolic equations are all "simple" we cannot guarantee that `u0` will be eagerly updated.

**Comment by kaandocal** [comment]
I really need to dig more into the initialisation mechanics of MTK. Adding such a note to the docs on `remake`/`replace` might help as well!

**Comment by kaandocal** [comment]
Sorry to bump this, but I've been repeatedly running into this issue. Depending on how you pass `u0` to `remake`, some variables are initialised, some aren't. For example, if I pass a copy of another solution's `u`, some variables are not updated; if I pass a vector of the form ':name => value', they are. Sadly I cannot provide a MWE at the moment, and this might have changed in post-Catalyst versions...

**Comment by ChrisRackauckas** [comment]
On the latest version? Using the symbolic init and not doing a numerical `u0`?
