### ISSUE TITLE
10.31.1 has issues with variable and equation counts

### ISSUE THREAD

**Issue by mx-p9a** [SciML/ModelingToolkit.jl#4048]
**Describe the bug 🐞**

I am seeing errors on 10.31.1 (but not on 10.31.0) like `ExtraEquationsSystemException: The system is unbalanced. There are 85 highest order derivative variables and 91 equations.`.

I can't share that code, so instead I ran on the Standard library and am also seeing errors there:

**Expected behavior**

Standard library's test to pass.

**Minimal Reproducible Example 👇**

```julia
@v1.12) pkg> test ModelingToolkitStandardLibrary
```

**Error & Stacktrace ⚠️**

```julia
Test Summary:                                | Pass  Fail  Error  Broken  Total      Time
Core                                         |  524     2      9       1    536  12m11.9s
  Blocks: utils                              |   12            1             13     19.7s
    Array Guesses                            |    2                           2      1.9s
    Scalarized Guesses                       |    4                           4      0.6s
    SISO Check                               |                 1              1     13.7s
  Blocks: math                               |   93                          93   1m16.3s
  Blocks: nonlinear                          |   15                          15     11.1s
  Blocks: continuous                         |   76                          76   1m03.9s
  Blocks: sources                            |   63                    1     64   2m44.7s
  Blocks: analysis points                    |   60                          60   2m00.6s
  Analog Circuits                            |   99                          99   1m48.1s
  Digital Circuits                           |   34                          34      0.9s
  Chua Circuit Demo                          |    1                           1      5.2s
  Thermal Circuits                           |   12     2      1             15     17.8s
    Heat systems                             |    6                           6      4.4s
    Heat flow system                         |                 1              1      0.8s
    Radiator system                          |    3                           3      2.3s
    Thermal Collector                        |    3                           3      1.7s
    FixedHeatFlow with alpha=0.0 test        |          2                     2      8.7s
  Thermal Demo                               |   10                          10     18.2s
  Magnetic                                   |    3                           3      3.8s
  Mechanical Rotation                        |   19            1             20     36.2s
    two inertias                             |    6                           6     12.6s
    two inertias with driving torque         |    6                           6      9.3s
    first example                            |    1                           1      6.2s
    Stick-Slip                               |    2                           2      4.4s
    sensors                                  |                 1              1      0.2s
    Position                                 |    4                           4      3.2s
  Mechanical Translation                     |   15            1             16     29.4s
    Free                                     |    2                           2      2.5s
    Spring, Damper, Mass, Fixed              |    4                           4     14.0s
    driven spring damper mass                |    4                           4      5.9s
    sources & sensors                        |    5            1              6      7.0s
      Translational                          |    3                           3      4.4s
      TranslationalPosition                  |    2            1              3      2.6s
        PositionSensor & ForceSensor         |    2                           2      2.3s
        AccelerationSensor                   |                 1              1      0.3s
  Mechanical Translation Modelica            |    7                           7      9.1s
  Multi-Domain                               |    2            2              4      4.8s
    DC motor                                 |                 1              1      0.3s
    DC motor with speed sensor               |                 1              1      0.1s
    Electrical Heating Circuit               |    2                           2      4.4s
  Hydraulic IsothermalCompressible           |    3            3              6     42.1s
    Fluid Domain and Tube                    |    2                           2     34.8s
    Valve                                    |    1                           1      4.7s
    DynamicVolume and minimum_volume feature |                 1              1      0.5s
    Actuator System                          |                 1              1      1.4s
    Prevent Negative Pressure                |                 1              1      0.3s
```
one of the errors:
```
Got exception outside of a @test
  ExtraVariablesSystemException: The system is unbalanced. There are 104 highest order derivative variables and 103 equations.
  More variables than equations, here are the potential extra variable(s):
  In particular, the unset input(s) are:
   pos₊s₊u(t)
  The rest of potentially unset variable(s) are:
   piston₊mass₊v(t)
   valve₊vSA₊x(t)
   valve₊vBR₊x(t)
   valve₊mass₊s(t)
   valve₊mass₊v(t)
   piston₊x(t)
   piston₊vol_a₊x(t)
   piston₊vol_a₊moving_volume₊x(t)
   piston₊vol_a₊moving_volume₊m(t)
   piston₊vol_b₊x(t)
   piston₊vol_b₊moving_volume₊x(t)
   piston₊vol_b₊moving_volume₊m(t)
   piston₊mass₊s(t)
   pos₊s₊u(t)
   pos₊flange₊f(t)
   snk₊port₊dm(t)
  Note that the process of determining extra variables is a best-effort heuristic. The true extra variables are dependent on the model and may not be in this list.
  Stacktrace:
```
(Interestingly only `ExtraVariablesSystemException`, not `ExtraEquationsSystemException`.

**Environment (please complete the following information):**
  - Output of `versioninfo()`

```julia
Julia Version 1.12.2
Commit ca9b6662be4 (2025-11-20 16:25 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: macOS (arm64-apple-darwin24.0.0)
  CPU: 12 × Apple M2 Max
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, apple-m2)
  GC: Built with stock GC
Threads: 1 default, 1 interactive, 1 GC (on 8 virtual cores)
Environment:
  JULIA_PKG_USE_CLI_GIT = true
```

**Comment by ChrisRackauckas** [comment]
@AayushSabharwal this was addressed? The related change for fully_determined?

**Comment by AayushSabharwal** [comment]
This doesn't look like the same bug. It's new.

**Comment by SebastianM-C** [comment]
I also noticed that the DC motor example fails with the extra variables error, but this seems to be because there is a mistake in the model that was exposed by a fix in MTK. In this case it looks like the support is missing an equation. More specifically, I added
```
emf.support.tau ~ emf.k * emf.i
```
and that fixed the issue.

**Comment by AayushSabharwal** [comment]
Oh, I see. Yeah, this is then likely the "inverse" of the issue that prompted the bug fix. Chris, I thought you meant that the fix wasn't complete that some systems still run into it.

**Comment by cstjean** [comment]
I still hit this. All of my tests on 10.31.0 pass locally, but on CI it loads 10.31.2 and it still fails just as it did on 10.31.1. It's not an MTKStdLib bug; it's in MTK 10.31.1

**Comment by cstjean** [comment]
The MTKStdLib [tests](https://github.com/SciML/ModelingToolkitStandardLibrary.jl/actions/runs/20259504749/job/58168284275#step:6:1525) of https://github.com/SciML/ModelingToolkitStandardLibrary.jl/pull/423 failed with exactly this ExtraEquationsSystemException error.

**Comment by AayushSabharwal** [comment]
It's not a bug, it's a bug fix that hid modeling issues. I'll try and explain in some detail. By default, `mtkcompile` runs with `fully_determined = true`, which tells MTK "my system is fully determined; it has the same number of equations and variables." MTK validates this to make sure, and checks for structurally singular systems. However, up until MTK@10.31.1 MTK used to run the `alias_elimination` pass before doing this validation. Under certain specific conditions, this pass adds equations to the system. However, if you say your system is fully determined, this shouldn't be necessary and adding these equations is incorrect. Since this pass ran prior to the check, it would add some equations that turn underdetermined systems into fully determined ones, which would subsequently pass the check and hide the model issue. We ran into cases where it was impossible to correctly initialize certain DAEs due to this. As a result, we perform the validation earlier now.

> failed with exactly this ExtraEquationsSystemException error.

As far as I can see, all of the failures are ExtraVariablesSystemException (not ExtraEquations...) which is exactly what is expected if the `alias_elimination` pass was artificially adding equations.

**Comment by cstjean** [comment]
Thank you for the explanation. My main code runs fine on 10.31.2, but this MWE code stopped working

```julia
using ModelingToolkit, Test, OrdinaryDiffEq
using ModelingToolkit: t_nounits as t, D_nounits as D

@mtkmodel SimpleFlowPin begin
    @variables begin
        flow(t)
        conc(t)
    end
end

connect_simple_flow(from, to::Vector) =
    vcat([from.conc ~ t.conc for t in to],
         from.flow + sum(t.flow for t in to) ~ 0)
connect_simple_flow(from::Vector, to) =
    vcat([to.conc ~ sum(f.conc * f.flow for f in from) / sum(f.flow for f in from)],
         to.flow + sum(f.flow for f in from) ~ 0)
connect_simple_flow(from, to) = connect_simple_flow([from], to) # (from, [to]) would also be fine

@mtkmodel Reactor begin  # mass-less reactor
    @components begin
        inlet = SimpleFlowPin()
        outlet = SimpleFlowPin()
    end
    @variables begin
        conc(t)  # ppm
    end
    @equations begin
        conc ~ inlet.conc + 0.2 # arbitrary, but whatever
        outlet.flow + inlet.flow ~ 0
        outlet.conc ~ conc
    end
end

@mtkmodel SimpleCirculationTank begin
    @components begin
        inlet = SimpleFlowPin()
        outlet = SimpleFlowPin()
    end
    @variables begin
        conc(t) = 0.2
    end
    @equations begin
        D(conc) ~ inlet.flow * inlet.conc + outlet.flow * conc
        0 ~ inlet.flow + outlet.flow

        outlet.conc ~ conc  # perfect mixing
    end
end

@mtkmodel ReactorTankLoop begin
    @components begin
        reactor1 = Reactor()
        reactor2 = Reactor()
        tank = SimpleCirculationTank()
    end
    @equations begin
        connect_simple_flow(tank.outlet, [reactor1.inlet, reactor2.inlet])
        connect_simple_flow([reactor1.outlet, reactor2.outlet], tank.inlet)

        reactor1.inlet.flow ~ 2
        reactor2.inlet.flow ~ 3
    end
end

# Stopped working on MTK v10.31.2
@mtkbuild rtl = ReactorTankLoop()
prob = ODEProblem(rtl, Dict(), (0, 100.0))
sol = solve(prob)
```
with
```julia
ERROR: LoadError: ExtraEquationsSystemException: The system is unbalanced. There are 15 highest order derivative variables and 16 equations.
More equations than variables, here are the potential extra equation(s):
 0 ~ tank₊outlet₊flow(t) + tank₊inlet₊flow(t)
```
Since my main code is fine, I'm not too concerned, but I thought it worth reporting.
